### ISSUE TITLE
Add support for GotR

### ISSUE THREAD

**Issue by FlowOverFail** [jpeter17/easy-empty#1]
Hi, are there any current plans to extend this to add support for Guardians of the Rift mini game?

**Comment by jpeter17** [comment]
I built this plugin with GoTR in mind so I could play without mouse only. 

Is there something that isn't working correctly at the moment? I am missing a few reqs for altars

**Comment by FlowOverFail** [comment]
Thanks for getting back quickly. At the Altars, I never saw an option for "Empty" for left click. I only saw the "Fill" option. Tried it on Nature, Law, and I believe one of the elementals but I cannot remember at the top of my head.

**Comment by jpeter17** [comment]
I'll do a round real quick and get back to you, those should all be working unless they changed something recently

**Comment by jpeter17** [comment]
[![gotr-min.gif](https://s7.gifyu.com/images/gotr-min.gif)](https://gifyu.com/image/SLud5)

Looks like things are working fine, do you have anything else turned on that might modify the menu options of the essence pouches?

**Comment by FlowOverFail** [comment]
Thanks for checking! I do have the customizable shift left-click for dropping items. Is there a way to check for this and work around it? I haven't tried to disable it, but the default option is to fill the pouch. Holding shift and left clicking will empty.

**Comment by jpeter17** [comment]
Strange, you might try a client restart and double checking the plugin is on 

After that take a screenshot of the right click options on the pouch both within and outside the altar and I can try to help further

**Comment by FlowOverFail** [comment]
Thanks for being so responsive by the way - I appreciate your time and support. I will get this to you once I am back on my laptop.

**Comment by FlowOverFail** [comment]
Actually I don't have any shift/left click modifying plugins (to my best knowledge). For both inside and outside the Altars, I get the following options in the same order:

- Fill
- Empty
- Check
- Use
- Drop
- Examine

**Comment by FlowOverFail** [comment]
Ah okay, with Menu Entry Swapper enabled that's when the "Empty" option doesn't appear inside the Altars. If this plugin is disabled, then I see "Empty". What is weird though is disabling the "Customizable left-click" and "shift-click" option doesn't change anything - only when disabling this plugin altogether. Are you able to replicate and troubleshoot this yourself?

**Comment by jpeter17** [comment]
If you enter left click configuration by right clicking the inventory icon is your left click set to empty for the pouches? The plugin works by swapping the fill and empty options conditonally

**Comment by Raisoshi** [comment]
What worked for to to fix this was:

Right click the backpack inventory icon, select configure left click, go over all runecrafting pouches left clicking them and selecting reset left click

Repeat the same for configure shift click(not sure this was necessary but I did it too).
