### ISSUE TITLE
Easy Empty causes client to crash when clicking "Fill Vyre well"  

### ISSUE THREAD

**Issue by nicknao** [jpeter17/easy-empty#4]
Hello, I know this isn't runecrafting related, but when the plugin is enabled and I click "Fill Vyre well" in Ver Sinhaza (Theatre of Blood bank) while the bank interface is open, the client crashes. Disabling the plugin allows you to click the well normally while having your bank open. Easily reproducible when re-enabling the plugin and repeating the action. Just figured I'd let you know!

OS: MacOS

**Comment by jpeter17** [comment]
This was brought to my attention in the RuneLite discord earlier today with the Fill option on the Giant's Foundry crucible, 310d68e8cf6bda6024c1348a8cee5fcd18219297 should fix this once the update is accepted by the RuneLite team
